spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Tute?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: p@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.edu.tute.schoolproject.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
#  servlet:
#    context-path: /api  # 添加API前缀
  port: 8080
  tomcat:
    uri-encoding: UTF-8 